# Generated by Django 2.0 on 2018-04-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('malignity', models.IntegerField()),
                ('package', models.TextField()),
                ('developer', models.TextField()),
                ('displayed_version', models.TextField()),
                ('added_on', models.DateField(auto_now_add=True)),
                ('size', models.PositiveIntegerField()),
                ('md5', models.TextField()),
                ('sha1', models.TextField()),
                ('sha256', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_feature', models.PositiveIntegerField()),
                ('extracted_on', models.DateField(auto_now_add=True)),
                ('apk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Apk')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='extract',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Feature'),
        ),
    ]
