# Generated by Django 2.0 on 2018-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apk',
            name='md5',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='sha1',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='apk',
            name='sha256',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
