# Generated by Django 2.0 on 2018-04-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180418_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousapi',
            name='api',
            field=models.TextField(unique=True),
        ),
    ]
